export const menu = [{
    id: 1,
    title: "Pratik Kahvaltı Tabağı",
    anaCategory: '',
    priority: 0,
    category: "Kahvaltı",
    price: "₺49",
    img: "https://twoplaidaprons.com/wp-content/uploads/2020/09/tteokbokki-top-down-view-of-tteokbokki-in-a-bowl-500x500.jpg",
    desc: `Patates Kızartması, Sosis, Beyaz Peynir, Kaşar Peyniri, Sigara Böreği, Domates,
    Salatalık, Iceberg, Bal, Tereyağı, Ortak Reçeller, Siyah Zeytin, Bir Bardak Çay`,
},
{
    id: 2,
    title: "Serpme Kahvaltı",
    anaCategory: '',
    priority: 0,
    category: "Kahvaltı",
    price: "<ol type=I start=2><li>₺160</li><li>₺190</li><li>₺220</li></ol>",
    img: "https://twoplaidaprons.com/wp-content/uploads/2020/09/tteokbokki-top-down-view-of-tteokbokki-in-a-bowl-500x500.jpg",
    desc: `Yeşil Zeytin, Siyah Zeytin, Beyaz Peynir, Çokokrem, Tereyağı, Acuka, Portakal Reçeli, Vişne Reçeli,
    Bal, Fındık Kreması, Kayısı Reçeli, Sosis, Sigara Böreği, Salam, Patates Kızartması, Iceberg,
    Domates, Salatalık, Sahanda Yumurta, Sahanda Sucuklu Yumurta, Kaşar Peyniri, Semaver Çay`,
},
{
    id: 3,
    title: "Elfida Konak Kahvaltı",
    anaCategory: '',
    priority: 0,
    category: "Kahvaltı",
    price: "<ol type=I start=2><li>₺220</li><li>₺250</li><li>₺280</li></ol>",
    img: "https://dwellbymichelle.com/wp-content/uploads/2020/05/DWELL-bibimbap.jpg",
    desc: `Menemen, Sucuklu Yumurta, Sigara Böreği, Sosis, Patates Kızartması, Biber Kızartması, 
    Gözleme, Siyah Zeytin, Yeşil Zeytin, Bal, Tereyağı, Çokokrem, Vişne Reçeli, Kayısı Reçeli, 
    Acuka, Fındık Kreması, Iceberg, Domates, Salatalık, Krep, Beyaz Peynir, Kaşar Peynir, Salam, 
    Örgü Peynir, Tulum Peynir, Kuru Kayısı, Kuru Üzüm, Portakal Reçeli, 1 Semaver Çay`,
},
{
    id: 4,
    title: "Sahanda Yumurta",
    anaCategory: '',
    priority: 0,
    category: "Sahanlar",
    price: "₺20",
    img: "https://www.savingdessert.com/wp-content/uploads/2019/02/Dan-Dan-Noodles-10.jpg",
    desc: ``,
},
{
    id: 5,
    title: "Sahanda Kaşarlı Yumurta",
    anaCategory: '',
    priority: 0,
    category: "Sahanlar",
    price: "₺22",
    img: "https://salu-salo.com/wp-content/uploads/2013/02/Yangzhou-Fried-Rice1.jpg",
    desc: ``,
},
{
    id: 6,
    title: "Sahanda Sucuklu Yumurta",
    anaCategory: '',
    priority: 0,
    category: "Sahanlar",
    price: "₺29",
    img: "https://www.manusmenu.com/wp-content/uploads/2017/08/Onigiri-3-1-of-1.jpg",
    desc: ``,
},
{
    id: 7,
    title: "Sahanda Kıymalı Yumurta",
    anaCategory: '',
    priority: 0,
    category: "Sahanlar",
    price: "₺34",
    img: "https://www.curiouscuisiniere.com/wp-content/uploads/2020/04/Jajangmyeon-Korean-Noodles-in-Black-Bean-Sauce5.1200H-720x540.jpg",
    desc: ``,
},
{
    id: 7,
    title: "Sahanda Kavurmalı Yumurta",
    anaCategory: '',
    priority: 0,
    category: "Sahanlar",
    price: "₺40",
    img: "https://www.curiouscuisiniere.com/wp-content/uploads/2020/04/Jajangmyeon-Korean-Noodles-in-Black-Bean-Sauce5.1200H-720x540.jpg",
    desc: ``,
},
{
    id: 8,
    title: "Menemen",
    anaCategory: '',
    priority: 0,
    category: "Sahanlar",
    price: "₺30",
    img: "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/F688C2F6-86EC-46C4-B9C7-A6BA01DF7437/Derivates/32E3E72A-F786-406D-AF7F-B30980A9AC6C.jpg",
    desc: `Sahanlar İstenilen Kıvamda Servis Edilir.`,
},
{
    id: 9,
    title: "Sucuklu Menemen",
    anaCategory: '',
    priority: 0,
    category: "Sahanlar",
    price: "₺37",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Sahanlar İstenilen Kıvamda Servis Edilir.`,
},
{
    id: 10,
    title: "Sade Omlet",
    anaCategory: '',
    priority: 0,
    category: "Omletler",
    price: "₺33",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Omletlerimiz Domates, Salatalık, Mevsim Yeşillikleri Patates Kızartması ve İki 
    Adet Özel Sos ile Servis Edilir.`,
},
{
    id: 11,
    title: "Kaşarlı Omlet",
    anaCategory: '',
    priority: 0,
    category: "Omletler",
    price: "₺35",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Omletlerimiz Domates, Salatalık, Mevsim Yeşillikleri Patates Kızartması ve İki 
    Adet Özel Sos ile Servis Edilir.`,
},
{
    id: 12,
    title: "Karışık Omlet",
    anaCategory: '',
    priority: 0,
    category: "Omletler",
    price: "₺38",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Salam, Sucuk Sosis, Mantar, Renkli Biberler, Taze Kaşar ve Mevsim Yeşillikleri.
    Omletlerimiz Domates, Salatalık, Mevsim Yeşillikleri Patates Kızartması ve İki 
    Adet Özel Sos ile Servis Edilir.`,
},
{
    id: 13,
    title: "Sade Gözleme",
    anaCategory: '',
    priority: 0,
    category: "Gözlemeler",
    price: "₺41",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 14,
    title: "Beyaz Peynirli Gözleme",
    anaCategory: '',
    priority: 0,
    category: "Gözlemeler",
    price: "₺42",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 15,
    title: "Kaşar Peynirli Gözleme",
    anaCategory: '',
    priority: 0,
    category: "Gözlemeler",
    price: "43",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 16,
    title: " Patatesli Kaşar Peynirli Gözleme",
    anaCategory: '',
    priority: 0,
    category: "Gözlemeler",
    price: "₺43",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 17,
    title: "Ispanaklı Kaşar Peynirli Gözleme",
    anaCategory: '',
    priority: 0,
    category: "Gözlemeler",
    price: "₺43",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 18,
    title: "Kıymalı Kaşar Peynirli Gözleme",
    anaCategory: '',
    priority: 0,
    category: "Gözlemeler",
    price: "₺46",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 19,
    title: "Karışık Gözleme",
    anaCategory: '',
    priority: 0,
    category: "Gözlemeler",
    price: "₺47",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `<a style=color:red>Salam, Sucuk, Sosis, Kaşar Peyniri</a>`,
},
{
    id: 20,
    title: "Kaşarlı Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺43",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 21,
    title: "Beyaz Peynirli Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺42",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 22,
    title: "Karışık Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺45",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `<a style=color:red>Salam, Sucuk, Sosis, Kaşar Peyniri</a>`,
},
{
    id: 23,
    title: "Kaşarlı Sucuklu Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺44",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 24,
    title: "Kavurmalı Kaşarlı Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺49",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 25,
    title: "Sanayi Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺51",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `<a style=color:red>Bakkal Ekmeği Arasına Sucuk, Yumurta, Kaşar Peyniri</a>`,
},
{
    id: 26,
    title: "Kaşarlı Bazlama Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺51",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 27,
    title: "Beyaz Peynirli Bazlama Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺51",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 28,
    title: "Sucuklu Bazlama Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺51",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 29,
    title: "Kavurmalı Bazlama Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺57",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 30,
    title: "Karışık Bazlama Tost",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺53",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `<a style=color:red>Salam, Sucuk, Kaşar Peyniri</a>`,
},
{
    id: 31,
    title: "Çıtır Patates",
    anaCategory: '',
    priority: 0,
    category: "Aperatifler",
    price: "₺49",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 32,
    title: "Elma Dilimli Patates",
    anaCategory: '',
    priority: 0,
    category: "Aperatifler",
    price: "₺49",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 33,
    title: "Sosis Sepeti",
    anaCategory: '',
    priority: 0,
    category: "Aperatifler",
    price: "₺55",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 34,
    title: "Nugget Sepeti",
    anaCategory: '',
    priority: 0,
    category: "Aperatifler",
    price: "₺55",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 35,
    title: "Soğan Halkası Sepeti",
    anaCategory: '',
    priority: 0,
    category: "Aperatifler",
    price: "₺55",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 36,
    title: "Sigara Böreği Sepeti",
    anaCategory: '',
    priority: 0,
    category: "Aperatifler",
    price: "₺50",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 37,
    title: "Çıtır Tavuk Sepeti",
    anaCategory: '',
    priority: 0,
    category: "Aperatifler",
    price: "₺58",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: ``,
},
{
    id: 38,
    title: "Elfida Sepeti",
    anaCategory: '',
    priority: 0,
    category: "Aperatifler",
    price: "₺61",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `<a style=color:red>Sigara Böreği, Patates Kroket, Çıtır Patates, Sosis, Nugget, Soğan Halkası</a>`,
},
{
    id: 39,
    title: "Hamburger",
    anaCategory: '',
    priority: 0,
    category: "Hamburger",
    price: "₺49",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Hamburger Ekmeği Arasına Iceberg, Domates, turşu, Hamburger Köftesi, Patates Kızartması, Soğan Halkası, Mevsim Yeşillikleri, Sos ile Sunulur`,
},
{
    id: 40,
    title: "Tekli Hamburger Menü",
    anaCategory: '',
    priority: 0,
    category: "Hamburger",
    price: "₺59",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tek Hamburger + Patates Kızartması + Kutu İçecek`,
},
{
    id: 41,
    title: "İkili Hamburger Menü",
    anaCategory: '',
    priority: 0,
    category: "Hamburger",
    price: "₺75",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `2 Adet Hamburger + Patates Kızartması + Kutu İçecek`,
},
{
    id: 42,
    title: "Cheese Burger",
    anaCategory: '',
    priority: 0,
    category: "Hamburger",
    price: "₺54",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Hamburger Ekmeği Arasına Iceberg, Domates, Turşu, Hamburger Köftesi Üzerine Cheddar Peynir, Patates Kızartması, Soğan Halklası, Mevsim Yeşillikleri ve Sos ile Sunulur`,
},
{
    id: 43,
    title: "Chicken Burger",
    anaCategory: '',
    priority: 0,
    category: "Hamburger",
    price: "₺48",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Hamburger Ekmeği Arasına Iceberg, Domates, Turşu, Özel Sos Hazırlanmış Tavuk Göğsü, Patates Kızartması, Soğan Halkası, Mevsim Yeşillikleri ve Özel Sos ile Sunulur.`,
},
{
    id: 44,
    title: "Double Burger",
    anaCategory: '',
    priority: 0,
    category: "Hamburger",
    price: "₺59",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Hamburger Ekmeği Arasında Çift Hamburger Eti, Iceberg, Turşu, Domates, Patates Kızartması, Soğan Halkası, Mevsim Yeşillikleri ve Özel Sos ile Sunulur`,
},
{
    id: 45,
    title: "Steak Burger",
    anaCategory: '',
    priority: 0,
    category: "Hamburger",
    price: "₺60",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Hamburger Ekmeği Arasında Dana Bonfile, Iceberg, Domates, Turşu, Marmasyon Sosu, Kuru Soğan, Köz Biber, Patates Kızartması, Soğan Halkası, Mevsim Yeşillikleri ve Özel Sos ile Sunulur`,
},
{
    id: 46,
    title: "Elfida Burger",
    anaCategory: '',
    priority: 0,
    category: "Hamburger",
    price: "₺66",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Hamburger Ekmeği Arasında 2 Adet Dana Burger Köfteler, 1 adet Tavuk Burger Köftesi, Dip Sos, Akdeniz Yeşillikleri, Cheddar Sos, Patates Kızartması ile ve Özel Sos ile Servis Edilir`,
},
{
    id: 47,
    title: "Doyuran Burger",
    anaCategory: '',
    priority: 0,
    category: "Tostlar",
    price: "₺58",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Hamburger Ekmeği Arasına Dana Burger, Karamelize Soğan, Akdeniz Yeşillikleri, Domates, Turşu, Patates Kızartması ve Özel Sos ile Servis Edilir`,
},
{
    id: 48,
    title: "Karışık Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella, Sucuk, Salam, Sosis, Mantar, Yeşil Biber, Kırmızı Biber, Siyah Zeytin, Yeşil Zeytin, Mısır ve Kekik`,
},
{
    id: 49,
    title: "Margarita Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella, Çeri Domates ve Kekik`,
},
{
    id: 50,
    title: "Dört Peynirli Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Hellim Peyniri, Cheddar Peynir, Beyaz Peynir ve Kekik`,
},
{
    id: 51,
    title: "Sucuklu Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Şerit Biber, Siyah Zeytin, Yeşil Zeytin, Sucuk ve Kekik`,
},
{
    id: 52,
    title: "Kalbim Ege'de",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Beyaz Peynir, Hellim Peynir, Kırmızı Soğan, Siyah Zeytin, Yeşil Zeytin, Patlıcan ve Kekik`,
},
{
    id: 53,
    title: "Standart Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Kırmızı Biber, Yeşil Biber, Siyah Zeytin, Yeşil Zeytin ve Kekik`,
},
{
    id: 54,
    title: "Tavuklu Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Marine Edilmiş Tavuk Göğsü, Kırmızı Biber, Mısır, Siyah Zeytin ve Kekik`,
},
{
    id: 55,
    title: "Meksika Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺75</li><li>₺90</li><li>₺105</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Kavrulmuş Kıyma, Meksika Fasulyesi, Jelapone Biber, Cheddar Peyniri, Kırmızı Soğan, Mısır ve Kekik`,
},
{
    id: 56,
    title: "Türk Gerçeği",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺75</li><li>₺90</li><li>₺105</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Pastırma, Sucuk, Kuru Soğan, Kırmızı Biber, Yeşil Biber, Siyah Zeytin, Ceviz ve Kekik`,
},
{
    id: 57,
    title: "Salamlı Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Şerit Biber, Siyah Zeytin, Yeşil Zeytin, Salam ve Kekik`,
},
{
    id: 58,
    title: "Ton Balıklı Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Ton Balığı, Kırmızı Biber, Yeşil Biber, Kırmızı Soğan, Mısır, Siyah Zeytin, Yeşil Zeytin ve Kekik`,
},
{
    id: 59,
    title: "Mantarlı Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Kırmızı Biber, Yeşil Biber, Zeytin, Mantar ve Kekik`,
},
{
    id: 60,
    title: "Vejeteryan Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Kabak, Patlıcan, Mısır, Kırmızı Biber, Yeşil Biber, Siyah Zeytin, Yeşil Zeytin ve Kekik`,
},
{
    id: 61,
    title: "Kavurmalı Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺75</li><li>₺90</li><li>₺105</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Kavurma, Kırmızı Biber, Yeşil Biber, Kırmızı Soğan, Mısır ve Kekik`,
},
{
    id: 62,
    title: "Sosisli Pizza",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺60</li><li>₺75</li><li>₺90</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Şerit Biber, Siyah Zeytin, Yeşil Zeytin, Sosis ve Kekik`,
},
{
    id: 63,
    title: "Elfida Special",
    anaCategory: '',
    priority: 0,
    category: "Pizzalar",
    price: "<ol type=I start=2><li>₺75</li><li>₺90</li><li>₺105</li></ol>",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Pizza Sos, Mozarella Peynir, Füme Kaburga, Mantar, Kırmızı Biber, Yeşil Biber, Mısır ve Kekik`,
},
{
    id: 64,
    title: "Elfida Kumpir",
    anaCategory: '',
    priority: 0,
    category: "Kumpir",
    price: "₺53",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Rus Salatası, Siyah Zeytin, Yeşil Zeytin, Mısır, Turşu, Sosis, Ketçap, Mayonez`,
},
{
    id: 65,
    title: "Etli Krep",
    anaCategory: '',
    priority: 0,
    category: "Essiz Lezzetler",
    price: "₺71",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Krep Ekmeği içerisinde Julyen Et, Mantar, Krema, Baharatlar, Patates Kızartması, Mevsim Yeşillikleri ve Sos Eşliğinde Servis Edilir`,
},
{
    id: 66,
    title: "Tavuklu Krep",
    anaCategory: '',
    priority: 0,
    category: "Essiz Lezzetler",
    price: "₺54",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Krep Ekmeği içerisinde Julyen Tavuk, Mantar, Krema, Baharatlar, Patates Kızartması, Mevsim Yeşillikleri ve Sos Eşliğinde Servis Edilir`,
},
{
    id: 67,
    title: "Taç Mahal (Kırmızı Et)",
    anaCategory: '',
    priority: 0,
    category: "Essiz Lezzetler",
    price: "₺89",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Bazlama Ekmeği Arasında Julyen Dana Bonfile, Mix Biber, Mantar, Kuru Soğan, Krema ve Şefin Özel Sosu, Bazlamanın Üzerinde Kaşar Peyniri, Dağ Kekiği ve Baharatlar, Patates Kızartması ve Soslar Eşliğinde Sunulur`,
},
{
    id: 68,
    title: "Taç Mahal (Beyaz Et)",
    anaCategory: '',
    priority: 0,
    category: "Essiz Lezzetler",
    price: "₺68",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Bazlama Ekmeği Arasında Julyen Tavuk Bonfile, Mix Biber, Mantar, Kuru Soğan, Krema ve Şefin Özel Sosu, Bazlamanın Üzerinde Kaşar Peyniri, Dağ Kekiği ve Baharatlar, Patates Kızartması ve Soslar Eşliğinde Sunulur`,
},
{
    id: 69,
    title: "Kıymalı Tortilla",
    anaCategory: '',
    priority: 0,
    category: "Essiz Lezzetler",
    price: "₺53",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tortilla Ekmeği Arasında Baharatlarla Lezzetlendirilmiş Kıyma ve Kaşar Peyniri, Patates Kızartması, Mevsim Yeşillikleri ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 70,
    title: "Tavuklu Tortilla",
    anaCategory: '',
    priority: 0,
    category: "Essiz Lezzetler",
    price: "₺52",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tortilla Ekmeği Arasında Baharatlarla Lezzetlendirilmiş Tavuk ve Kaşar Peyniri, Patates Kızartması, Mevsim Yeşillikleri ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 71,
    title: "Etli Tortilla",
    anaCategory: '',
    priority: 0,
    category: "Essiz Lezzetler",
    price: "₺73",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tortilla Ekmeği Arasında Baharatlarla Lezzetlendirilmiş Et ve Kaşar Peyniri, Patates Kızartması, Mevsim Yeşillikleri ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 72,
    title: "Kaşar Peynirli Tortilla",
    anaCategory: '',
    priority: 0,
    category: "Essiz Lezzetler",
    price: "₺54",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tortilla Ekmeği Arasında Cheddar Peyniri ve Kaşar Peyniri, Patates Kızartması, Mevsim Yeşillikleri ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 73,
    title: "Beyaz Peynirli Sandviç",
    anaCategory: '',
    priority: 0,
    category: "Sandviçler",
    price: "₺36",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Sandviç Ekmeği Arası Beyaz Peynir ve Yeşillik`,
},
{
    id: 74,
    title: "Soğuk Sandviç",
    anaCategory: '',
    priority: 0,
    category: "Sandviçler",
    price: "₺37",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Sandviç Ekmeği Arasında Kaşar Peyniri, Salam, Yeşillik, Domates, Turşu, Patates Kızartması, Mevsim Yeşillikleri ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 75,
    title: "Ton Balıklı Sandviç",
    anaCategory: '',
    priority: 0,
    category: "Sandviçler",
    price: "₺44",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Sandviç Ekmeği Arasında Turşu, Yeşillik ve Ton Balığı, Patates Kızartması, Mevsim Yeşillikleri ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 76,
    title: "Köfte Sandviç",
    anaCategory: '',
    priority: 0,
    category: "Sandviçler",
    price: "₺49",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Sandviç Ekmeği Arasında Yeşillik, Domates, Turşu ve Izgara Köfte, Patates Kızartması, Mevsim Yeşillikleri ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 77,
    title: "Clup Sandviç",
    anaCategory: '',
    priority: 0,
    category: "Sandviçler",
    price: "₺46",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Sandviç Ekmeği Arasında Izgara Tavuk Göğsü, Üzerinde Eritilmiş Cheddar Peyniri, Yeşillik ve Turşu, Patates Kızartması, Mevsim Yeşillikleri ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 78,
    title: "Tavuklu Sandviç",
    anaCategory: '',
    priority: 0,
    category: "Sandviçler",
    price: "₺43",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Sandviç Ekmeği Arasında Tavuk Parçaları, Renkli Biber, Mantar, Kuru Soğan, Özel Kremalı Sos, Patates Kızartması, Mevsim Yeşillikleri ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 79,
    title: "Et Sandviç",
    anaCategory: '',
    priority: 0,
    category: "Sandviçler",
    price: "₺66",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Sandviç Ekmeği Arasında Julyen Doğranmış Dana Bonfile, Renkli Biber, Mantar, Kuru Soğan, Özel Kremalı Sos, Patates Kızartması, Mevsim Yeşillikleri ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 80,
    title: "Izgara Köfte",
    anaCategory: '',
    priority: 0,
    category: "Köfteler",
    price: "₺69",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Özel Baharatlarla Hazırlanmış El Yapımı 5 Adet Izgara Köfte, Pilav, Köz Biber, Köz Domates, Mevsim Yeşillikleri, Patates Kızartması ve Sos Eşliğinde Servis Edilir`,
},
{
    id: 81,
    title: "Şefin Nefis Köftesi",
    anaCategory: '',
    priority: 0,
    category: "Köfteler",
    price: "₺75",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tereyağında Sotelenmiş Bazlama Küpleri, Üzerinde Yoğurt ve Öz Baharatlarla Hazırlanmış El Yapımı 6 Adet Izgara Köfte, Köz Biber, Köz Domates, Köz Kuru Soğan ve Tereyağlı Sos ile Servis Edilir`,
},
{
    id: 82,
    title: "Kaşarlı Köfte",
    anaCategory: '',
    priority: 0,
    category: "Köfteler",
    price: "₺78",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Özel Baharatlarla Hazırlanmış El Yapımı 2 Adet 130gr Köfte, Üzerine Eritilmiş Kaşar Peyniri, Pilav, Köz Biber, Köz Domates, Mevsim Yeşillikleri, Patates Kızartması ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 83,
    title: "Et Wrap",
    anaCategory: '',
    priority: 0,
    category: "Wraplar",
    price: "₺68",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tortilla Ekmeği Arasında Julyen Doğranmış Dana Bonfile, Biber, Mix, Mantar Kuru Soğan Maydanoz, Kaşar Peyniri, Soya Sosu, Yeşillik Mix, Patates Kızartması ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 84,
    title: "Tavuk Wrap",
    anaCategory: '',
    priority: 0,
    category: "Wraplar",
    price: "₺51",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tortilla Ekmeği Arasında Julyen Doğranmış Tavuk Bonfile, Biber, Mix, Mantar Kuru Soğan Maydanoz, Kaşar Peyniri, Soya Sosu, Yeşillik Mix, Patates Kızartması ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 85,
    title: "Köfte Wrap",
    anaCategory: '',
    priority: 0,
    category: "Wraplar",
    price: "₺55",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tortilla Ekmeği Arasında Izgara Köfte, Domates, Turşu, Iceberg, Kaşar Peyniri, Yeşillik Mix, Patates Kızartması ve Özel Sos Eşliğinde Servis Edilir`,
},
{
    id: 86,
    title: "Köri Soslu Tavuk",
    anaCategory: '',
    priority: 0,
    category: "Beyaz Etler",
    price: "₺69",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tavuk Parçaları, Mantar, Biber Mix, Köri Sosu, Krema, Patates Kızartması, Yeşillik Mix ve Özel Sos Eşliğinde Sunulur`,
},
{
    id: 87,
    title: "Barbekü Soslu Tavuk",
    anaCategory: '',
    priority: 0,
    category: "Beyaz Etler",
    price: "₺69",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tavuk Parçaları, Biber Mix, Barbekü Sos, Patates Kızartması, Yeşillik Mix ve Özel Sos Eşliğinde Sunulur`,
},
{
    id: 88,
    title: "Chili Soslu Tavuk",
    anaCategory: '',
    priority: 0,
    category: "Beyaz Etler",
    price: "₺71",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tavuk Parçaları, Biber Mix, Mantar, Mısır, Patates Kızartması, Yeşillix Mix ve Özel Sos Eşliğinde Sunulur`,
},
{
    id: 89,
    title: "Tavuk Sote",
    anaCategory: '',
    priority: 0,
    category: "Beyaz Etler",
    price: "₺71",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tavuk Parçaları, Biber Mix, Mantar, Kuru Soğan, Domates, Patates Kızartması, Yeşillik Mix ve Özel Sos Eşliğinde Sunulur`,
},
{
    id: 90,
    title: "Tavuk Parapella",
    anaCategory: '',
    priority: 0,
    category: "Beyaz Etler",
    price: "₺71",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tavuk Parçaları, Biber Mix, Mantar, Kuru Soğan, Krema, Parapella Sosu, Patates Kızartması, Yeşillik Mix ve Özel Sos Eşliğinde Sunulur`,
},
{
    id: 91,
    title: "Dağ Kekikli Tavuk",
    anaCategory: '',
    priority: 0,
    category: "Beyaz Etler",
    price: "₺74",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Izgara Tavuk Külbastı Üzerine Kaşar Peyniri ve Dağ Kekiği, Patates Kızartması, Yeşillik Mix ve Özel Sos Eşliğinde Sunulur`,
},
{
    id: 92,
    title: "Tavuk Külbastı",
    anaCategory: '',
    priority: 0,
    category: "Beyaz Etler",
    price: "₺74",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Izgara Tavuk, Köz Biber, Köz Domates, Pilav, Yeşillik Mix, Patates Kızartması, Yeşillik Mix ve Özel Sos Eşliğinde Sunulur`,
},
{
    id: 93,
    title: "Tavuk Çökertme",
    anaCategory: '',
    priority: 0,
    category: "Beyaz Etler",
    price: "₺78",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Tereyağında Sotelenmiş Bazlama Ekmeği, Yoğurt, Mix Biber, Domates ile Sotelenmiş Tavuk Parçalarıi Kibrit Patates ve Şefin Özel Sosu Eşliğinde Sunulur`,
},
{
    id: 94,
    title: "Tavuk Fajita",
    anaCategory: '',
    priority: 0,
    category: "Beyaz Etler",
    price: "₺78",
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Izgara Tavuk, Kuru Soğan, Mix Biber, Tortilla Ekmeği, Acı Biber Turşusu, Rendelenmiş Kaşar Peyniri ve Acı Sos ile Servis Edilir`,
},
{
    id: 95,
    title: 'Et Sote',
    anaCategory: '',
    priority: 0,
    category: 'Kırmızı Etler',
    price: '₺88',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Dana Bonfile,Renkli Biberler, Kuru Soğan,Sarımsak Ve Domatesle Marine Edilmiş Enfes Bir Lezzet,Pilav,Patates Kızartması Mevsim Yeşillikleri Yada Mevsimine  Göre Sebze Mix Eşliğinde Servis Edilir.`,
},
{
    id: 96,
    title: 'Dana Külbastı',
    anaCategory: '',
    priority: 0,
    category: 'Kırmızı Etler',
    price: '₺95',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Marine EdilmişIzgara DAna Bonfile, Pilav ,Köz Biber, Köz Domates, Köz Kuru Soğan, Patates Kızartması, Mevsim Yeşillikleri Yada Mevsimine Göre Sebze Mix Eşliğinde Servis Edillir `,
},
{
    id: 97,
    title: 'Saç Kavurma',
    anaCategory: '',
    category: 'Kırmızı Etler',
    priority: 0,
    price: '₺95',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Saçta Kavrulmuş Dana Bonfile, Biber Mix, Kuru Soğan, Sarımsak,Domates,Dağ Kekiği Ve Plav Eşliğinde Servis Edilir.`,
},
{
    id: 98,
    title: 'Et Çökertme',
    anaCategory: '',
    category: 'Kırmızı Etler',
    priority: 0,
    price: '₺95',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Tereyağında Sotelenmiş Bazlama Ekmeği Üzerine Yoğurt,Kibrit Patets,Marine Edilmiş Dana BonfileDilimleri,Biber Mix,Özel Domates Sos Ve Şefin Özel Sosu Eşliğinde Servis Edilir.`,
}, {
    id: 98,
    title: 'Mantar Soslu Dana Bonfile',
    anaCategory: '',
    category: '',
    priority: 0,
    price: '₺95',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Marine Edilmiş Izgara Dana Bonfile, Üzerine Sotelenmiş Mantar,Krema ve Demi Glace Sos,Pilav,Köz Biber,Köz Domates,Köz Kuru Soğan,Patates Kızartması,Mevsim Yeşillikleri Yada Mevsimine Göre Sebze Mix Eşliğinde Servs Edilir.`,
},
{
    id: 98,
    title: 'Et Fajita',
    anaCategory: '',
    category: 'Kırmızı Etler',
    priority: 0,
    price: '₺95',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Marine Edilmiş Izgara Dana Bonfile, Kuru Soğan, Mix Biber, Tortilla Ekmeği, Turşu, Rendelenmiş Kaşar Peyniri VE Özel Sos ile Servs Edilir.`,
},
{
    id: 100,
    title: 'Çikolatalı Pasta',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Muzlu Pasta',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Meyveli Pasta',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Çilekli Pasta',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Frambuazlı Bella',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Orman Meyveli Pasta',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Kara Orman Meyveli Pasta',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Devils Cake',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Fıstık Rüyası',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Çikolatalı Penaut',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Gökküşağı Pasta',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Red Velvet',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Siyah Profiterollü',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 100,
    title: 'Bisküvili Pasta',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺44',
    img: '',
    desc: ``,
},
{
    id: 99,
    title: 'Akdeniz Salatası',
    anaCategory: '',
    priority: 10,
    category: 'Salatalar',
    price: '₺36',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Mevsim Yeşillikleri, Beyaz Peynir, Domates, Salatalık, Havuç, Mısır, Zeytin ve Özel Sos ile Servis Edilir`,
},
{
    id: 99,
    title: 'Ton Balıklı Salata',
    anaCategory: '',
    priority: 10,
    category: 'Salatalar',
    price: '₺42',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Mevsim Yeşillikleri, Mısır, Turşu, Zeytin, Havuç, Domates, Salatalık, Ton Balığı ve Salata Sos ile`,
},
{
    id: 99,
    title: 'Barbekü Soslu Tavuk Satala',
    priority: 10,
    anaCategory: '',
    category: 'Salatalar',
    price: '₺41',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Mevsim Yeşillikleri, Barbekü Soslu Tavuk, Mısır, Havuç, Turşu, Domates, Salatalık ile Servis Edilir`,
},
{
    id: 99,
    title: 'Sezar Salata',
    anaCategory: '',
    category: 'Salatalar',
    priority: 10,
    price: '₺41',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Iceberg, Baharatlı Izgara Tavuk, Domates, Salatalık, Mısır, Craton Ekmek, Turşu ve Sezar Sos ile Sunulur`,
},
{
    id: 99,
    title: 'Çıtır Tavuk Salata',
    anaCategory: '',
    category: 'Salatalar',
    priority: 10,
    price: '₺41',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Mevsim Yeşillikleri, Havuç, Mısır, Domates, Salatalık, Zeytin, Kızartılmış Çıtır Tavuk ve Hardal Sos ile`,
},
{
    id: 99,
    title: 'Çoban Salata',
    anaCategory: '',
    category: 'Salatalar',
    priority: 10,
    price: '₺34',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Domates, Salatalık, Biber, Maydanoz, Nar Ekşisi, Acı Sos, (İsteğe Göre Soğan)`,
},
{
    id: 99,
    title: 'Mevsim Salata',
    anaCategory: '',
    category: 'Salatalar',
    priority: 10,
    price: '₺36',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Mevsimine Göre Taze Yeşil Mix ile Hazırlanır`,
},

//
{
    id: 100,
    title: 'Waffle',
    anaCategory: '',
    priority: 0,
    category: 'Tatlılar',
    price: '₺48',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Waffle Ekmeği Üzerine Mükemmel Akça Çikolatasıyla, Muz, Çilek ile Muhteşem Buluşması`,
},
{
    id: 100,
    title: 'Suffle',
    anaCategory: '',
    priority: 0,
    category: 'Talılar',
    price: '₺43',
    img: 'https://via.placeholder.com/500x400.png',
    desc: `Sıcak ve Dondurma ile İkram Edilir`,
},
{
    id: 100,
    title: 'Sütlaç',
    anaCategory: '',
    priority: 0,
    category: 'Tatlılar',
    price: '₺31',
    img: 'https://via.placeholder.com/500x400.png',
    desc: ``,
},
{
    id: 100,
    title: 'Ekler',
    anaCategory: '',
    priority: 0,
    category: 'Tatlılar',
    price: '₺43',
    img: 'https://via.placeholder.com/500x400.png',
    desc: ``,
},
{
    id: 100,
    title: 'Triliçe',
    anaCategory: '',
    priority: 0,
    category: 'Tatlılar',
    price: '₺40',
    img: 'https://via.placeholder.com/500x400.png',
    desc: ``,
},
{
    id: 100,
    title: 'Kuru Pasta',
    anaCategory: '',
    priority: 0,
    category: 'Pastalar',
    price: '₺33',
    img: 'https://via.placeholder.com/500x400.png',
    desc: ``,
},
{
    id: 100,
    title: 'Kuruyemiş',
    anaCategory: '',
    priority: 0,
    category: 'Kuruyemiş',
    price: '₺52',
    img: 'https://via.placeholder.com/500x400.png',
    desc: ``,
},
{
    id: 100,
    title: 'Çiğ Köfte',
    anaCategory: '',
    priority: 0,
    category: 'Çiğ Köfte',
    price: '<ol><li>Dürüm: ₺160</li><li>Servis: ₺190</li></ol>',
    img: 'https://via.placeholder.com/500x400.png',
    desc: ``,
},
{
    id: 100,
    title: 'Klasik Meyve Tabağı',
    anaCategory: '',
    priority: 0,
    category: 'Meyve',
    price: '₺75',
    img: 'https://via.placeholder.com/500x400.png',
    desc: ``,
},
{
    id: 100,
    title: 'Elfida Meyve Tabağı',
    anaCategory: '',
    priority: 0,
    category: 'Meyve',
    price: '₺135',
    img: 'https://via.placeholder.com/500x400.png',
    desc: ``,
}
    ,
{
    id: 100,
    title: 'Demleme Bardak Çay',
    anaCategory: '',
    priority: 0,
    category: 'Sıcak İçcecekler',
    price: '₺8',
    img: 'https://via.placeholder.com/500x400.png',
    desc: ``,
},
{
    id: 98,
    title: 'Demleme Fincan Çay',
    anaCategory: '',
    category: 'Sıcak İçecekler',
    priority: 0,
    price: '₺14',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Süt',
    anaCategory: '',
    category: 'Sıcak İçecekler',
    priority: 0,
    price: '₺14',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Sahlep',
    anaCategory: '',
    category: 'Sıcak İçecekler',
    priority: 0,
    price: '₺23',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Oralet Çeşitleri',
    anaCategory: '',
    category: 'Sıcak İçecekler',
    priority: 0,
    price: '₺11',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Kış Çayı',
    anaCategory: '',
    category: 'Sıcak İçecekler',
    priority: 0,
    price: '₺24',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Kuşburnu',
    anaCategory: '',
    category: 'Sıcak İçecekler',
    priority: 0,
    price: '₺24',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Ihlamur',
    anaCategory: '',
    category: 'Sıcak İçecekler',
    priority: 0,
    price: '₺24',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Rezene',
    anaCategory: '',
    category: 'Sıcak İçecekler',
    priority: 0,
    price: '₺24',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Ada Çayı',
    anaCategory: '',
    category: 'Sıcak İçecekler',
    priority: 0,
    price: '₺24',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Semaverde Çay',
    anaCategory: '',
    category: 'Sıcak İçecekler',
    priority: 0,
    price: '₺85',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Filtre Kahve',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺31',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Americano',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺30',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Espresso',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺30',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Cade Mocha',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺30',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Cappucino',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺32',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Latte',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺32',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Aromalı Latte',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺34',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Sade Nescafe',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺30',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Nescafe 3ü 1 Arada',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺30',
    img: '',
    desc: ``,
},
{
    id: 98,
    title: 'Sütlü Nescafe',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺30',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Ice Latte',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺34',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Aromalı Ice Latte',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺35',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Ice Mocha',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺35',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Sade Sıcak Çikolata',
    anaCategory: '',
    category: 'Sıcak Çikolata',
    priority: 0,
    price: '₺25',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Muzlu Sıcak Çikolata',
    anaCategory: '',
    category: 'Sıcak Çikolata',
    priority: 0,
    price: '₺25',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Sütlü Sıcak Çikolata',
    anaCategory: '',
    category: 'Sıcak Çikolata',
    priority: 0,
    price: '₺25',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Türk Kahvesi',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺27',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Sütlü Türk Kahvesi',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺28',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Menengiç Kahvesi',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺27',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Paşanın Dibeği',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺27',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Aromalı Türk Kahveleri',
    anaCategory: '',
    category: 'Kahveler',
    priority: 0,
    price: '₺28',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Limonlu Milkshake',
    anaCategory: '',
    category: 'Milkshake',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Karpuz-Çilekli Milkshake',
    anaCategory: '',
    category: 'Milkshake',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Muzlu Milkshake',
    anaCategory: '',
    category: 'Milkshake',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Çikolatalı Milkshake',
    anaCategory: '',
    category: 'Milkshake',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Vanilyalı Milkshake',
    anaCategory: '',
    category: 'Milkshake',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Frambuazlı Milkshake',
    anaCategory: '',
    category: 'Milkshake',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Kivili Milkshake',
    anaCategory: '',
    category: 'Milkshake',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Çilekli Frozen',
    anaCategory: '',
    category: 'Frozen',
    priority: 0,
    price: '₺43',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Kavunlu Frozen',
    anaCategory: '',
    category: 'Frozen',
    priority: 0,
    price: '₺43',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Karpuzlu Frozen',
    anaCategory: '',
    category: 'Frozen',
    priority: 0,
    price: '₺43',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Çilekli Smoothie',
    anaCategory: '',
    category: 'Smoothie',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Muzlu Smoothie',
    anaCategory: '',
    category: 'Smoothie',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Çikolatalı Smoothie',
    anaCategory: '',
    category: 'Smoothie',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Vanilyalı Smoothie',
    anaCategory: '',
    category: 'Smoothie',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Frambuazlı Smoothie',
    anaCategory: '',
    category: 'Smoothie',
    priority: 0,
    price: '₺39',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Churcill',
    anaCategory: '',
    category: 'Soğuk İçecekler',
    priority: 0,
    price: '₺27',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Kutu İçecekler',
    anaCategory: '',
    category: 'Soğuk İçecekler',
    priority: 0,
    price: '₺28',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Enerji İçeceği',
    anaCategory: '',
    category: 'Soğuk İçecekler',
    priority: 0,
    price: '₺31',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Limonata',
    anaCategory: '',
    category: 'Soğuk İçecekler',
    priority: 0,
    price: '₺25',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Aromalı Limonata',
    anaCategory: '',
    category: 'Soğuk İçecekler',
    priority: 0,
    price: '₺27',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Meyveli Soda',
    anaCategory: '',
    category: 'Soğuk İçecekler',
    priority: 0,
    price: '₺18',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Soda',
    anaCategory: '',
    category: 'Soğuk İçecekler',
    priority: 0,
    price: '₺13',
    img: '',
    desc: ``,
},
{
    id: 0,
    title: 'Ayran',
    anaCategory: '',
    category: 'Soğuk İçecekler',
    priority: 0,
    price: '₺8',
    img: '',
    desc: ``,
}, {
    id: 0,
    title: 'Spagetti Bolonez',
    anaCategory: '',
    category: 'Makarnalar',
    priority: 0,
    price: '₺59',
    img: '',
    desc: `Spagetti Makarnası, Şefin Özel Kıymalı Bolonez Sosu, Kaşar Peyniri, Dilim Zeytin ile Servis Edilir`,
},
{
    id: 0,
    title: 'Spagetti Napoliten',
    anaCategory: '',
    category: 'Makarnalar',
    priority: 0,
    price: '₺58',
    img: '',
    desc: `Spagetti Makarnası, Özel Domates Sosu, Kaşar Peyniri, Siyah Zeytin ile Servis Edilir`,
},
{
    id: 0,
    title: 'Fettucini Alfredo',
    anaCategory: '',
    category: 'Makarnalar',
    priority: 0,
    price: '₺61',
    img: '',
    desc: `Fettucini Makarnası, Julyen Doğranmış Tavuk, Mantar, Krema, Cheddar Peyniri ve Alfredo Sos ile Servis Edilir`,
},
{
    id: 0,
    title: 'Köri Soslu Fettucini Alfredo',
    anaCategory: '',
    category: 'Makarnalar',
    priority: 0,
    price: '₺61',
    img: '',
    desc: `Fettucini Makarnası,  Julyen Doğranmış Tavuk, Mantar, Krema, Cheddar Peyniri ve Köri Sos ile Servis Edilir`,
},
{
    id: 0,
    title: 'Pesto Soslu Penne',
    anaCategory: '',
    category: 'Makarnalar',
    priority: 0,
    price: '₺61',
    img: '',
    desc: `Penne Makarnası, Julyen Doğranmış Dana Bonfile, Siyah Dilim Zeytin, Kaşar Peyniri, Pesto Sos ve Domates Sosu ile Servis Edilir`,
},
{
    id: 0,
    title: 'Penne Arabiatta',
    anaCategory: '',
    category: 'Makarnalar',
    priority: 0,
    price: '₺61',
    img: '',
    desc: `Penne Makarnası Siyah Dilim Zeytin, Kaşar Peyniri, Domates Sos ve Acı Sos ile Servis Edilir `,
},
{
    id: 0,
    title: 'Tavuklu Noodle',
    anaCategory: '',
    category: 'Makarnalar',
    priority: 0,
    price: '₺67',
    img: '',
    desc: `Noodle Makarnası, Julyen Doğranmış Tavuk Bonfile, Julyen Doğranmış Havuç, Kuru Soğan, Beyaz Lahana, Brokoli, Chili Sos, Soya Sos ve Özel Baharatlarla Tatlandırılmış Enfes Bir Lezzet`,
},
{
    id: 0,
    title: 'Etli Noodle',
    anaCategory: '',
    category: 'Makarnalar',
    priority: 0,
    price: '₺71',
    img: '',
    desc: `Noodle Makarnası, Julyen Doğranmış Dana Bonfile, Julyen Doğranmış Havuç, Kuru Soğan, Beyaz Lahana, Brokoli, Chili Sos, Soya Sos ve Özel Baharatlarla Tatlandırılmış Enfes Bir Lezzet`,
},

];